version: "3.8"

services:
  mysql-todo:
    image: mysql:latest
    platform: linux/amd64
    container_name: mysql-todo
    ports:
      - "3306:3306"
    networks:
      - net-todo
    volumes:
      - db_todo_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

networks:
  net-todo:

volumes:
  db_todo_mysql:
